### ISSUE TITLE
Scala CLI mode in Scastie

### ISSUE THREAD

**Issue by julienrf** [scalacenter/student-projects#10]
## Description

[Scastie](https://scastie.scala-lang.org) is an online Scala playground that allows everyone to write, run, and share Scala programs from their web browser.

Currently, Scastie allows users to configure their programs by exposing its sbt build definition. Users can add dependencies and set compiler options, for instance. This approach has several drawbacks:
- the configuration of the program is separate from its code,
- in order to run a program locally, users have to download a zip file containing an sbt project definition, and then use `sbt`.

As an alternative, we would like to allow the users to configure their program via [Scala CLI directives](https://scala-cli.virtuslab.org/docs/guides/configuration#using-directives). This would solve the issues mentioned above: the configuration would be part of the source code (as magic comments), and copying the program content to a local file would be enough to execute it locally (with `scala-cli run`).

Corresponding issue: scalacenter/scastie#603

## Expected Outcome

Scastie supports a Scala CLI mode where the program configuration is defined with standard Scala CLI directives.

More specifically:
- in the “settings” screen, users could choose between sbt (current), or Scala CLI mode
- the program compilation and execution (on the server-side) will be managed by Scala CLI
- a Metals language server instance (running on the server) will enable IDE features on the client-side
- the code editor (on the client-side) will properly highlight the syntax of Scala CLI directives

## Supervisors

[Julien Richard-Foy](https://github.com/julienrf) (julien.richard-foy@epfl.ch): Technical director of the Scala Center.
[Jędrzej Rochala](https://github.com/rochala) (jrochala@virtuslab.com): Software engineer at VirtusLab.

**Comment by julienrf** [comment]
Taken by @Maeeen

**Comment by kubukoz** [comment]
Is this already available in Scastie? I don't see anything non-sbt-specific in the web version, and directives don't seem to work OOTB.

**Comment by rochala** [comment]
@kubukoz The implementation has been finished 3 weeks ago and the PR is waiting for the review. Hopefully it will be merged in January.

**Comment by kubukoz** [comment]
Thanks for the update!

**Comment by Krever** [comment]
Hey @rochala, was this released? I can't find the switch anywhere in the UI.

**Comment by rochala** [comment]
Nah, sadly the PR that introduces it grew to enormous size (basically the original architecture never assumed to support 2 tools at the same time, and after 40% of code was changed I decided to actually refactor it to be maintainable...). At the moment it compiles and kinda works, but still there are few refactors to be made.

That said, I don't see spending any time on this in the near future (not because I don't want to, I just don't have time / have other priorities)
