### ISSUE TITLE
Java support in Metals

### ISSUE THREAD

**Issue by adpi2** [scalacenter/student-projects#6]
## Description

[Metals](https://scalameta.org/metals/) is the Scala language server for code editors like VS Code.

Metals provides the implementations of a lot of IDE features, such as goto definition, hover, find references, for the Scala language only.
But Scala is compatible with Java and many projects mix Scala and Java dependencies, Scala and Java sources.
So it would be very useful if Metals could also support those features for the Java language.

There are a few Java language servers already that we could reuse to implement those features. One of them, [georgewfraser/java-language-server](https://github.com/georgewfraser/java-language-server) uses the Java compiler API directly, which might be the simplest approach for us.

Related feature request in Metals is: https://github.com/scalameta/metals-feature-requests/issues/5
It is the most wanted feature, by the community currently.

## Supervisors

[Adrien Piquerez](https://github.com/adpi2)(adrien.piquerez@epfl.ch): Tooling Engineer at the Scala Center
[Tomasz Godzik](https://github.com/tgodzik): Tooling Engineer at Virtus Lab and the Scala Center, main maintainer of Metals

## Prerequisites

- Some experience with Scala and Java
- Ideally some experience with Metals, or LSP servers

## Expected Outcome

Added support for Java on some important features of Metals.

**Comment by dos65** [comment]
@adpi2 @tgodzik

Hey! I found a student who is interested in taking this project and I will be able to provide full mentoship for him.
Will it be fine?
Also, I need to make sure that this project isn't taken yet by anyone.

**Comment by tgodzik** [comment]
Great to hear @dos65 ! I don't think the project got started at any point. It would be amazing if the student would be able to at least provide a single new feature such as hover etc. They might first need to take a look at what would be the best approach here.

**Comment by dos65** [comment]
Cool, then we will start working on that with @VankaTaganai.

> They might first need to take a look at what would be the best approach here.

Yep we will start from that. I think we will publish the investigation results here or in scameta/metals to discuss which will be the best one.

**Comment by adpi2** [comment]
> Cool, then we will start working on that with @VankaTaganai.

 That's a great news. Thanks for picking up that project @VankaTaganai and @dos65.
I am marking the issue as taken.
